# Generated by Django 2.0 on 2021-12-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(default='no email', max_length=50)),
                ('bank', models.CharField(choices=[('BMO', 'BMO'), ('RBC', 'RBC'), ('CIBC', 'CIBC'), ('TD', 'TD'), ('SCOTIA BANK', 'SCOTIA BANK')], max_length=50)),
                ('card', models.CharField(max_length=50)),
                ('card_note', models.CharField(max_length=550)),
            ],
        ),
    ]
