# Generated by Django 2.0 on 2021-12-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_user', models.CharField(blank=True, max_length=50, null=True)),
                ('card', models.CharField(blank=True, max_length=10, null=True)),
                ('trans_date', models.DateField()),
                ('trans_time', models.TimeField(blank=True, null=True)),
                ('trans_location', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
